name: ci

on: push

jobs:

  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - run: |
      bash ci/prepare_ubuntu20.sh
      bash ci/setup_gbench.sh
      make configure
      make build
      make run 
      make bench