name: ci

on: push

jobs:

  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2

    - name: Prepare
      run: |
        sudo bash ci/prepare_ubuntu20.sh
        bash ci/setup_gbench.sh
        make configure
        make build

    - name: Run
      run: |
        make run 
        make bench